### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by allmyfdisgay** [Pazdikan/dbd-xp-farm#3]
I have set up all the environment variables and installed the necessary libraries, but when I run the program, nothing happens. The program just keeps moving the mouse to the top-left corner without any further action.

**Comment by Pazdikan** [comment]
Check out the screenshot.png file. It should be a small rectangle of the start/continue button area. Is it? Maybe it screenshots another display, however I use dual monitor setup with the script without any issues.

**Comment by allmyfdisgay** [comment]
Its not.................


***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pazdikan/dbd-xp-farm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 凌晨0:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pazdikan/dbd-xp-farm] nothing works (Issue #3)





 
Check out the screenshot.png file. It should be a small rectangle of the start/continue button area. Is it? Maybe it screenshots another display, however I use dual monitor setup with the script without any issues.

**Comment by Pazdikan** [comment]
Are you sure you are using 1080p resolution in windows? Do you have a second display, that's set to the left from the main display?

**Comment by allmyfdisgay** [comment]
I run this with 1920x1080 resolution in game and 2560x1440 in windows there are two display, my main display is 2560x1440 second play is 2560x1600



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pazdikan/dbd-xp-farm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 凌晨0:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pazdikan/dbd-xp-farm] nothing works (Issue #3)





 
Are you sure you are using 1080p resolution in windows? Do you have a second display, that's set to the left from the main display?

**Comment by Pazdikan** [comment]
As stated in the yellow highlighted warning in the readme, you have to set the monitor display to 1080p.

Yes, this is inconvenient but I'm too lazy to work on an area selector lol

**Comment by allmyfdisgay** [comment]
thx a lot for help！！！！！





***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pazdikan/dbd-xp-farm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 凌晨1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pazdikan/dbd-xp-farm] nothing works (Issue #3)





 
As stated in the yellow highlighted warning in the readme, you have to set the monitor display to 1080p.
 
Yes, this is inconvenient but I'm too lazy to work on an area selector lol

**Comment by Pazdikan** [comment]
No problem, enjoy using the script!
